# Generated by Django 6.0.7 on 2026-07-31 05:31

import common.models
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderConnection',
            fields=[
                ('id', models.UUIDField(default=common.models.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(help_text="Unique within the organization, e.g. 'pretalx-pyohio-2026'.", max_length=100)),
                ('name', models.CharField(help_text="Display name, e.g. 'PyOhio Pretalx (2026)'.", max_length=200)),
                ('capability', models.CharField(choices=[('talk_source', 'Talk source'), ('ticketing', 'Ticketing'), ('video_host', 'Video host')], max_length=32)),
                ('provider', models.CharField(help_text="Registered provider name, e.g. 'pretalx'.", max_length=64)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('credentials_encrypted', models.TextField(blank=True, editable=False)),
                ('is_active', models.BooleanField(default=True)),
                ('last_verified_at', models.DateTimeField(blank=True, help_text='Last time these credentials were confirmed working.', null=True)),
                ('last_verify_error', models.TextField(blank=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provider_connections', to='events.organization')),
            ],
            options={
                'ordering': ['organization', 'capability', 'slug'],
            },
        ),
        migrations.CreateModel(
            name='EventProviderBinding',
            fields=[
                ('id', models.UUIDField(default=common.models.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('capability', models.CharField(choices=[('talk_source', 'Talk source'), ('ticketing', 'Ticketing'), ('video_host', 'Video host')], max_length=32)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provider_bindings', to='events.event')),
                ('connection', models.ForeignKey(help_text="Must belong to the event's organization and provide this capability.", on_delete=django.db.models.deletion.PROTECT, related_name='bindings', to='integrations.providerconnection')),
            ],
            options={
                'ordering': ['event', 'capability'],
            },
        ),
        migrations.CreateModel(
            name='SyncRun',
            fields=[
                ('id', models.UUIDField(default=common.models.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('capability', models.CharField(choices=[('talk_source', 'Talk source'), ('ticketing', 'Ticketing'), ('video_host', 'Video host')], max_length=32)),
                ('provider', models.CharField(max_length=64)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('succeeded', models.BooleanField(default=False)),
                ('error', models.TextField(blank=True)),
                ('counts', models.JSONField(blank=True, default=dict)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_runs', to='events.event')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.AddIndex(
            model_name='providerconnection',
            index=models.Index(fields=['organization', 'capability'], name='integration_organiz_874662_idx'),
        ),
        migrations.AddConstraint(
            model_name='providerconnection',
            constraint=models.UniqueConstraint(fields=('organization', 'slug'), name='unique_connection_slug_per_org'),
        ),
        migrations.AddConstraint(
            model_name='eventproviderbinding',
            constraint=models.UniqueConstraint(fields=('event', 'capability'), name='unique_binding_per_event_capability'),
        ),
        migrations.AddIndex(
            model_name='syncrun',
            index=models.Index(fields=['event', 'capability', '-started_at'], name='integration_event_i_d9f8b0_idx'),
        ),
    ]
