# Generated by Django 6.0.7 on 2026-08-05 05:16

import common.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_organizationmembership_scopes'),
        ('integrations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderWrite',
            fields=[
                ('id', models.UUIDField(default=common.models.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('capability', models.CharField(choices=[('talk_source', 'Talk source'), ('ticketing', 'Ticketing'), ('video_host', 'Video host')], max_length=32)),
                ('operation', models.CharField(choices=[('set_privacy', 'Set privacy'), ('upload_captions', 'Upload captions')], max_length=32)),
                ('target_external_id', models.CharField(help_text="The provider's id for the thing being written.", max_length=128)),
                ('desired', models.JSONField(default=dict)),
                ('result', models.JSONField(blank=True, default=dict)),
                ('state', models.CharField(choices=[('pending', 'Pending'), ('in_flight', 'In flight'), ('confirmed', 'Confirmed'), ('failed', 'Failed'), ('superseded', 'Superseded')], default='pending', max_length=20)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('last_error', models.TextField(blank=True)),
                ('not_before', models.DateTimeField(blank=True, help_text='Earliest this may be attempted. Set by a quota deferral or a scheduled release.', null=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provider_writes', to='events.event')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='provider_writes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['state', 'not_before'], name='integration_state_8354c8_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('state', 'pending')), fields=('event', 'target_external_id', 'operation'), name='one_pending_write_per_target_and_operation')],
            },
        ),
    ]
