# Generated by Django 6.0.7 on 2026-08-05 04:34

import common.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0002_organizationmembership_scopes'),
        ('program', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.UUIDField(default=common.models.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('external_id', models.CharField(help_text="Provider's video id, e.g. a YouTube video id.", max_length=128)),
                ('title', models.CharField(blank=True, max_length=500)),
                ('description', models.TextField(blank=True)),
                ('privacy_status', models.CharField(choices=[('private', 'Private'), ('unlisted', 'Unlisted'), ('public', 'Public')], default='private', help_text='As last reported by the provider.', max_length=20)),
                ('duration_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('published_at', models.DateTimeField(blank=True, help_text="Provider's upload timestamp.", null=True)),
                ('standalone', models.BooleanField(default=False, help_text='Deliberately has no talk: a welcome, closing remarks, a keynote recording. Reviewed and approved by staff rather than by a speaker.')),
                ('matched_at', models.DateTimeField(blank=True, null=True)),
                ('review_state', models.CharField(choices=[('pending', 'Pending'), ('invited', 'Invited'), ('changes_requested', 'Changes requested'), ('approved', 'Approved')], default='pending', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('publication_state', models.CharField(choices=[('unpublished', 'Unpublished'), ('scheduled', 'Scheduled'), ('published', 'Published')], default='unpublished', max_length=20)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_videos', to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='events.event')),
                ('matched_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matched_videos', to=settings.AUTH_USER_MODEL)),
                ('talk', models.ForeignKey(blank=True, help_text='Null until matched. A talk may have more than one video.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='videos', to='program.talk')),
            ],
            options={
                'ordering': ['title', 'external_id'],
                'indexes': [models.Index(fields=['event', 'review_state'], name='videos_vide_event_i_30833e_idx'), models.Index(fields=['event', 'publication_state'], name='videos_vide_event_i_e40217_idx')],
                'constraints': [models.UniqueConstraint(fields=('event', 'external_id'), name='unique_video_external_id_per_event'), models.CheckConstraint(condition=models.Q(('standalone', False), ('talk__isnull', True), _connector='OR'), name='standalone_video_has_no_talk')],
            },
        ),
    ]
