# Generated by Django 6.0.7 on 2026-07-31 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='from_email',
            field=models.EmailField(blank=True, help_text="Sender address for this organization's mail. Blank uses the deployment default. The domain must be verified with the email provider.", max_length=254),
        ),
        migrations.AddField(
            model_name='organization',
            name='from_name',
            field=models.CharField(blank=True, help_text="Display name shown alongside the sender address, e.g. 'PyOhio'. Defaults to the organization name.", max_length=100),
        ),
    ]
