# Generated by Django 6.0.7 on 2026-08-05 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationmembership',
            name='scopes',
            field=models.JSONField(blank=True, default=list, help_text='Domain scopes this membership grants. Leave empty to grant all of them.'),
        ),
    ]
