# Generated by Django 6.0.7 on 2026-08-05 03:53

import common.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0002_organizationmembership_scopes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Speaker',
            fields=[
                ('id', models.UUIDField(default=common.models.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('external_id', models.CharField(help_text="Provider's speaker code, e.g. Pretalx 'TXY7EW'.", max_length=128)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, help_text='Where review invitations go.', max_length=254)),
                ('biography', models.TextField(blank=True)),
                ('avatar_url', models.URLField(blank=True, max_length=500)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='speakers', to='events.event')),
                ('user', models.ForeignKey(blank=True, help_text='Set when this speaker first logs in. Null until then.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='speaker_profiles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Talk',
            fields=[
                ('id', models.UUIDField(default=common.models.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('external_id', models.CharField(help_text="Provider's submission code.", max_length=128)),
                ('title', models.CharField(max_length=500)),
                ('abstract', models.TextField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('duration_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('session_type', models.CharField(blank=True, help_text="e.g. 'Talk', 'Keynote'.", max_length=100)),
                ('state', models.CharField(blank=True, help_text="Provider's state, e.g. 'confirmed'.", max_length=50)),
                ('scheduled_start', models.DateTimeField(blank=True, null=True)),
                ('scheduled_end', models.DateTimeField(blank=True, null=True)),
                ('do_not_record', models.BooleanField(default=False, help_text='Speaker or organizer opted out of recording. Blocks publication entirely.')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='talks', to='events.event')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='TalkSpeaker',
            fields=[
                ('id', models.UUIDField(default=common.models.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('speaker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='talk_speakers', to='program.speaker')),
                ('talk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='talk_speakers', to='program.talk')),
            ],
            options={
                'ordering': ['talk', 'speaker'],
            },
        ),
        migrations.AddField(
            model_name='talk',
            name='speakers',
            field=models.ManyToManyField(related_name='talks', through='program.TalkSpeaker', to='program.speaker'),
        ),
        migrations.AddIndex(
            model_name='speaker',
            index=models.Index(fields=['event', 'email'], name='program_spe_event_i_12ed53_idx'),
        ),
        migrations.AddConstraint(
            model_name='speaker',
            constraint=models.UniqueConstraint(fields=('event', 'external_id'), name='unique_speaker_external_id_per_event'),
        ),
        migrations.AddConstraint(
            model_name='talkspeaker',
            constraint=models.UniqueConstraint(fields=('talk', 'speaker'), name='unique_talk_speaker'),
        ),
        migrations.AddIndex(
            model_name='talk',
            index=models.Index(fields=['event', 'state'], name='program_tal_event_i_303861_idx'),
        ),
        migrations.AddConstraint(
            model_name='talk',
            constraint=models.UniqueConstraint(fields=('event', 'external_id'), name='unique_talk_external_id_per_event'),
        ),
    ]
